apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "{{ values.name | replace('_', '-') | lower }}"
  title: "{{ values.name }}"
  description: "{{ values.description }}"
  annotations:
    github.com/project-slug: "itcne/{{ values.name }}"
    backstage.io/techdocs-ref: dir:.
  tags:
    - ansible
    - execution-environment
    - automation
    - container
spec:
  type: service
  lifecycle: experimental
  owner: "{{ values.owner }}"
  system: ansible-automation
  providesApis:
    - "{{ values.name }}-ee-api"

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "{{ values.name }}-ee-api"
  description: "Containerized Ansible Execution Environment for running playbooks"
  tags:
    - ansible
    - automation
spec:
  type: container
  lifecycle: experimental
  owner: "{{ values.owner }}"
  definition:
    $text: |
      Provides a containerized execution environment for Ansible playbooks.
      Base Image: "{{ values.baseImage }}"
      Includes custom dependencies for "{{ values.name }}".
