apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  title: ${{ values.name | dump }}
  description: ${{ values.description | dump }}
  annotations:
    github.com/project-slug: ${{ ("itcne/" + values.name) | dump }}
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://github.com/itcne/sem05_devhub_templates/tree/main/ansible-ee-template
  tags:
    - ansible
    - execution-environment
    - container
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner | dump }}
  system: ansible-automation
