---
# Ansible Galaxy Collections required for this execution environment

collections:
  # Core Ansible collections - recommended for most environments
  - name: ansible.posix
    version: ">=1.5.4"

${{ values.requiredCollections.map(collection => `  - name: ${collection}`).join('\n') }}
