---
# Ansible Galaxy Collections required for this execution environment

collections:
  # Core Ansible collections - recommended for most environments
  - name: ansible.posix
    version: ">=1.5.4"
    
{% for collection in values.requiredCollections %}
{% if ':' in collection %}
{% set parts = collection.split(':') %}
  - name: "{{ parts[0] }}"
    version: "{{ parts[1] }}"
{% else %}
  - name: "{{ collection }}"
{% endif %}
{% endfor %}