---
# Ansible Galaxy Collections required for this execution environment

collections:
{%- for collection in values.requiredCollections %}
{%- if collection %}
{%- if ':' in collection %}
{%- set parts = collection.split(':') %}
  - name: ${{ parts[0] }}
    version: ${{ parts[1] }}
{%- else %}
  - name: ${{ collection }}
{%- endif %}
{%- endif %}
{%- endfor %}