---
# Ansible Galaxy Collections required for this execution environment

collections:
{%- for collection in (values.requiredCollections | fromJson if values.requiredCollections is string else values.requiredCollections) -%}
  {%- set parts = collection.split(':') -%}
  - name: "{{ parts[0] }}"
    {%- if parts|length > 1 %}
    version: "{{ parts[1] }}"
    {%- endif %}
{% endfor -%}
